bind 0.0.0.0
protected-mode no
port 6379
dir /data

cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
cluster-require-full-coverage yes
cluster-preferred-endpoint-type hostname

appendonly yes
appendfsync everysec
save 60 1000

replica-read-only yes
repl-backlog-size 16mb
latency-monitor-threshold 100
slowlog-log-slower-than 10000
slowlog-max-len 128
