/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    id("org.springframework.boot") version "4.0.0"
    id("io.spring.dependency-management") version "1.1.7"
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter") // manage dependency
    implementation("org.springframework.boot:spring-boot-starter-jdbc")
    implementation ("org.springframework.boot:spring-boot-starter-mail")
    runtimeOnly("com.h2database:h2")
    compileOnly("org.projectlombok:lombok")
    annotationProcessor("org.projectlombok:lombok")

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testImplementation("org.springframework.boot:spring-boot-starter-test")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testCompileOnly("org.projectlombok:lombok")
    testAnnotationProcessor("org.projectlombok:lombok")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType<Test> {
    useJUnitPlatform()

    // 테스트 실행 중 로그 출력
    testLogging {
        events(
//            "passed",
            "skipped",
            "failed")
    }

    // 테스트 완료 후 요약 리포트 출력
    addTestListener(object : TestListener {
        override fun beforeSuite(suite: TestDescriptor) {}
        override fun beforeTest(testDescriptor: TestDescriptor) {}
        override fun afterTest(testDescriptor: TestDescriptor, result: TestResult) {}

        override fun afterSuite(suite: TestDescriptor, result: TestResult) {
            // 모든 테스트가 끝난 시점(Root Suite)에만 출력
            if (suite.parent == null) {
                println("\nTest Result: ${result.resultType}")
                println("Total Tests: ${result.testCount}")
                println("Successes: ${result.successfulTestCount}")
                println("Failures: ${result.failedTestCount}")
                println("Skipped: ${result.skippedTestCount}\n")
            }
        }
    })
}

// ./gradlew :app:beanPostProcessorDemo
tasks.register<JavaExec>("beanPostProcessorDemo") {
    group = "application"
    description = "BeanPostProcessor 학습용 데모를 실행합니다."
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("com.jungbum.beanPostProcessor.BeanPostProcessorDemo")
}

// ./gradlew :app:beanFactoryPostProcessorDemo
tasks.register<JavaExec>("beanFactoryPostProcessorDemo") {
    group = "application"
    description = "BeanFactoryPostProcessor 학습용 데모를 실행합니다."
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("com.jungbum.bean.BeanFactoryPostProcessorDemo")
}

// ./gradlew :app:beanDefinitionDemo
tasks.register<JavaExec>("beanDefinitionDemo") {
    group = "application"
    description = "BeanDefinition 학습용 데모를 실행합니다."
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("com.jungbum.bean.BeanDefinitionDemo")
}

tasks.register<JavaExec>("beanLifecycleDemo") {
    group = "application"
    description = "스프링 빈 전체 생명주기 학습용 데모를 실행합니다."
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("com.jungbum.bean.BeanLifecycleDemo")
}

tasks.register<JavaExec>("realisticLifecycleDemo") {
    group = "application"
    description = "실무에 가까운 빈 생명주기(생성자 주입 + @PostConstruct/@PreDestroy) 데모를 실행합니다."
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("com.jungbum.bean.RealisticLifecycleDemo")
}
